name: Build flatpak asan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_flatpak_asan:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@master
    secrets: inherit
    with:
      with_asan: true
      debug_symbols: true
      actions_branch: master
