name: Build osx

on:
  push:
  workflow_dispatch:

jobs:
  build_osx:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@master
    secrets: inherit
    with:
      actions_branch: master
