name: Create flatpak single file bundle

on:
  workflow_dispatch:

jobs:
  bundle_flatpak:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/bundle_flatpak.yml@master
    secrets: inherit
    with:
      actions_branch: master
